"""initial

Revision ID: 051209ffe8dd
Revises: 
Create Date: 2026-08-14 15:31:10.720835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '051209ffe8dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imoveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fonte', sa.Enum('caixa', 'zukerman', name='fonte'), nullable=False),
    sa.Column('id_externo', sa.String(length=100), nullable=True),
    sa.Column('url_edital', sa.String(length=500), nullable=True),
    sa.Column('tipo', sa.Enum('residencial', 'comercial', 'terreno', name='tipoimovel'), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('bairro', sa.String(length=150), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('regiao', sa.String(length=100), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('metragem', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fonte', 'id_externo', name='uq_imovel_fonte_externo')
    )
    op.create_table('analises_financeiras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('valor_mercado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fonte_valor_mercado', sa.String(length=500), nullable=True),
    sa.Column('iptu_debito', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('condominio_debito', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('iptu_mensal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('condominio_mensal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('meses_carregamento', sa.Integer(), nullable=False),
    sa.Column('comissao_corretor_revenda', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('margem_minima_corte', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valor_arremate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_registro_cartorio', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_itbi', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('custo_carregamento', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ir_ganho_capital', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_custos', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('margem_liquida_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('margem_liquida_valor', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('resultado', sa.Enum('viavel', 'nao_viavel', name='resultadoanalise'), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('editais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('valor_minimo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_avaliacao', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('desconto_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('financiamento', sa.String(length=100), nullable=True),
    sa.Column('modalidade_venda', sa.String(length=100), nullable=True),
    sa.Column('data_1a_praca', sa.Date(), nullable=True),
    sa.Column('valor_1a_praca', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('data_2a_praca', sa.Date(), nullable=True),
    sa.Column('valor_2a_praca', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('comissao_leiloeiro', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('responsabilidade_divida_iptu', sa.Enum('credor', 'arrematante', 'nao_informado', name='responsabilidadedivida'), nullable=True),
    sa.Column('responsabilidade_divida_condominio', sa.Enum('credor', 'arrematante', 'nao_informado', name='responsabilidadedivida'), nullable=True),
    sa.Column('imovel_foreiro', sa.Boolean(), nullable=True),
    sa.Column('responsabilidade_foro_laudemio', sa.String(length=300), nullable=True),
    sa.Column('condicoes_pagamento', sa.Text(), nullable=True),
    sa.Column('possui_vaga_garagem_separada', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imovel_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('editais')
    op.drop_table('analises_financeiras')
    op.drop_table('imoveis')
    # ### end Alembic commands ###
