"""add_caracteristicas_imovel

Revision ID: 0fbdf80db07b
Revises: c3f9a2e10b47
Create Date: 2026-08-17 15:47:50.660589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fbdf80db07b'
down_revision: Union[str, Sequence[str], None] = 'c3f9a2e10b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imoveis', sa.Column('area_total_m2', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('imoveis', sa.Column('area_privativa_m2', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('imoveis', sa.Column('area_terreno_m2', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('imoveis', sa.Column('quartos', sa.Integer(), nullable=True))
    op.add_column('imoveis', sa.Column('salas', sa.Integer(), nullable=True))
    op.add_column('imoveis', sa.Column('vagas_garagem', sa.Integer(), nullable=True))
    op.add_column('imoveis', sa.Column('possui_wc', sa.Boolean(), nullable=True))
    op.add_column('imoveis', sa.Column('possui_cozinha', sa.Boolean(), nullable=True))
    op.add_column('imoveis', sa.Column('descricao_parsing_incompleto', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.drop_column('imoveis', 'metragem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imoveis', sa.Column('metragem', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('imoveis', 'descricao_parsing_incompleto')
    op.drop_column('imoveis', 'possui_cozinha')
    op.drop_column('imoveis', 'possui_wc')
    op.drop_column('imoveis', 'vagas_garagem')
    op.drop_column('imoveis', 'salas')
    op.drop_column('imoveis', 'quartos')
    op.drop_column('imoveis', 'area_terreno_m2')
    op.drop_column('imoveis', 'area_privativa_m2')
    op.drop_column('imoveis', 'area_total_m2')
    # ### end Alembic commands ###
