"""add_importacoes_planilha

Revision ID: 2cb287523617
Revises: 0fbdf80db07b
Create Date: 2026-08-17 21:23:37.305601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2cb287523617'
down_revision: Union[str, Sequence[str], None] = '0fbdf80db07b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('importacoes_planilha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fonte', postgresql.ENUM('caixa', 'zukerman', name='fonte', create_type=False), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=300), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('sucesso', 'erro', name='statusimportacao'), nullable=False),
    sa.Column('imoveis_importados', sa.Integer(), nullable=True),
    sa.Column('imoveis_ignorados', sa.Integer(), nullable=True),
    sa.Column('mensagem_erro', sa.Text(), nullable=True),
    sa.Column('iniciado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finalizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('importacoes_planilha')
    # ### end Alembic commands ###
