"""add_extraction_jobs_envelopes

Revision ID: 4e04805f44aa
Revises: 2cb287523617
Create Date: 2026-08-18 15:01:42.155583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e04805f44aa'
down_revision: Union[str, Sequence[str], None] = '2cb287523617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('agente_tipo', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'em_execucao', 'concluido', 'falhou', 'requer_revisao', name='statusjob'), nullable=False),
    sa.Column('prioridade', sa.String(length=20), nullable=False),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('max_tentativas', sa.Integer(), nullable=False),
    sa.Column('input_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disponivel_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(), nullable=True),
    sa.Column('finalizado_em', sa.DateTime(), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_imovel_agente', 'extraction_jobs', ['imovel_id', 'agente_tipo'], unique=False)
    op.create_index('ix_jobs_status_disponivel', 'extraction_jobs', ['status', 'disponivel_em'], unique=False)
    op.create_table('extraction_envelopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('agente_tipo', sa.String(length=50), nullable=False),
    sa.Column('versao_agente', sa.String(length=20), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('fonte', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('campos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('campos_nao_encontrados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observacoes_agente', sa.Text(), nullable=True),
    sa.Column('extraido_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['extraction_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_envelope_imovel_agente_versao', 'extraction_envelopes', ['imovel_id', 'agente_tipo', 'versao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_envelope_imovel_agente_versao', table_name='extraction_envelopes')
    op.drop_table('extraction_envelopes')
    op.drop_index('ix_jobs_status_disponivel', table_name='extraction_jobs')
    op.drop_index('ix_jobs_imovel_agente', table_name='extraction_jobs')
    op.drop_table('extraction_jobs')
    # ### end Alembic commands ###
