"""add_custos_extras_analise

Revision ID: 6ebaf5eccbf7
Revises: 051209ffe8dd
Create Date: 2026-08-14 22:46:54.793679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ebaf5eccbf7'
down_revision: Union[str, Sequence[str], None] = '051209ffe8dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analises_financeiras', sa.Column('custo_advogado', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('analises_financeiras', sa.Column('custo_reforma', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('analises_financeiras', sa.Column('outros_custos', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('analises_financeiras', sa.Column('outros_custos_descricao', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analises_financeiras', 'outros_custos_descricao')
    op.drop_column('analises_financeiras', 'outros_custos')
    op.drop_column('analises_financeiras', 'custo_reforma')
    op.drop_column('analises_financeiras', 'custo_advogado')
    # ### end Alembic commands ###
