"""planilha_fonte_verdade

Revision ID: c19e613e303d
Revises: 4e04805f44aa
Create Date: 2026-08-31 18:40:43.715559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19e613e303d'
down_revision: Union[str, Sequence[str], None] = '4e04805f44aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'imoveis',
        sa.Column('ativo', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    )
    op.add_column('imoveis', sa.Column('desativado_em', sa.DateTime(), nullable=True))
    op.add_column('imoveis', sa.Column('data_planilha_origem', sa.Date(), nullable=True))
    op.create_index('ix_imoveis_fonte_uf_ativo', 'imoveis', ['fonte', 'uf', 'ativo'], unique=False)
    op.add_column('importacoes_planilha', sa.Column('data_geracao', sa.Date(), nullable=True))
    op.add_column('importacoes_planilha', sa.Column('ufs_processadas', sa.String(length=200), nullable=True))
    op.add_column('importacoes_planilha', sa.Column('imoveis_atualizados', sa.Integer(), nullable=True))
    op.add_column('importacoes_planilha', sa.Column('imoveis_desativados', sa.Integer(), nullable=True))
    op.add_column('importacoes_planilha', sa.Column('avisos', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('importacoes_planilha', 'avisos')
    op.drop_column('importacoes_planilha', 'imoveis_desativados')
    op.drop_column('importacoes_planilha', 'imoveis_atualizados')
    op.drop_column('importacoes_planilha', 'ufs_processadas')
    op.drop_column('importacoes_planilha', 'data_geracao')
    op.drop_index('ix_imoveis_fonte_uf_ativo', table_name='imoveis')
    op.drop_column('imoveis', 'data_planilha_origem')
    op.drop_column('imoveis', 'desativado_em')
    op.drop_column('imoveis', 'ativo')
    # ### end Alembic commands ###
